name: Secret Scan Pipeline

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GitLeaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64
          chmod +x gitleaks-linux-amd64
          sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

      - name: Run GitLeaks
        run: gitleaks detect --exit-code 1